from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from typing import List, Dict, Any

from app.database import get_db
from app.models import TeachingPolicy
from app.schemas import PolicyGenerateRequest, TeachingPolicySchema
from app.services.groq_service import groq_service

router = APIRouter(prefix="/api/policies", tags=["Teaching Policies"])

@router.post("/generate", response_model=List[TeachingPolicySchema])
def generate_policies(request: PolicyGenerateRequest, db: Session = Depends(get_db)):
    # Call Groq API service for 5-10 strategies
    raw_policies = groq_service.generate_teaching_policies(
        topic=request.topic,
        difficulty=request.difficulty_level,
        target_group=request.target_group
    )

    created_policies = []
    for item in raw_policies:
        policy = TeachingPolicy(
            topic=request.topic,
            difficulty_level=request.difficulty_level,
            target_group=request.target_group,
            title=item.get("title", f"Adaptive Strategy for {request.topic}"),
            description=item.get("description", "Dynamic policy generated by CL-CATT system."),
            expected_outcome=float(item.get("expected_outcome", 0.88)),
            confidence_score=float(item.get("confidence_score", 0.92)),
            risk_score=float(item.get("risk_score", 0.12)),
            causal_reasoning=item.get("causal_reasoning", "Causal pathway optimizes prerequisite recall before concept application."),
            groq_explanation=item.get("groq_explanation", "Synthesized using Groq LLaMA 3.3 70B architecture.")
        )
        db.add(policy)
        created_policies.append(policy)

    db.commit()
    for p in created_policies:
        db.refresh(p)

    return created_policies

@router.get("", response_model=List[TeachingPolicySchema])
def get_policies(db: Session = Depends(get_db)):
    return db.query(TeachingPolicy).order_by(TeachingPolicy.id.desc()).limit(20).all()
